import type { NextPage } from 'next'
import Head from 'next/head'
import FormPage from '../templates/FormPage'

const Home: NextPage = () => {
  return (
    <main>
      <Head>
        <title>Teste técnico | William Coscodai</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        
        
      </Head>
      <FormPage />
    </main>
  )
}

export default Home
